apiVersion: v1
description: Mojaloop Helm chart for Kubernetes
name: mojaloop
version: 10.1.0
appVersion: "ml-api-adapter: v10.1.1; central-ledger: v10.1.1; account-lookup-service: v10.1.0; quoting-service: v10.1.1; central-settlement: v9.5.0; central-event-processor: v9.5.0; bulk-api-adapter: v9.5.0-snapshot; email-notifier: v9.5.0; als-oracle-pathfinder: v8.7.1; transaction-requests-service: v10.1.2; finance-portal-ui: v9.4.0; finance-portal-backend-service: v9.4.5; settlement-management: v8.8.2; operator-settlement: v9.2.1; simulator: v9.5.0; mojaloop-simulator: v9.4.1; sdk-scheme-adapter: v10.1.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
dependencies:
- name: central
  version: 9.3.0
  repository: "file://../central"
  condition: central.enabled
- name: ml-api-adapter
  version: 9.3.0
  repository: "file://../ml-api-adapter"
  condition: ml-api-adapter.enabled
- name: emailnotifier
  version: 9.3.0
  repository: "file://../emailnotifier"
  condition: emailnotifier.enabled
- name: account-lookup-service
  version: 9.3.0
  repository: "file://../account-lookup-service"
  condition: account-lookup-service.enabled
- name: quoting-service
  version: 9.3.0
  repository: "file://../quoting-service"
  condition: quoting-service.enabled
- name: simulator
  version: 9.3.0
  repository: "file://../simulator"
  condition: simulator.enabled
- name: mojaloop-bulk
  version: 9.3.0
  repository: "file://../mojaloop-bulk"
  condition: mojaloop-bulk.enabled
- name: transaction-requests-service
  version: 9.3.0
  repository: "file://../transaction-requests-service"
  condition: transaction-requests-service.enabled
- name: finance-portal
  version: 9.3.0
  repository: "file://../finance-portal"
  condtion: finance-portal.enabled
- name: finance-portal-settlement-management
  version: 9.3.0
  repository: "file://../finance-portal-settlement-management"
  condition: finance-portal-settlement-management.enabled
