apiVersion: v1
version: 10.1.0
appVersion: "account-lookup-service: v10.1.0; als-oracle-pathfinder: v9.4.0"
description: Account Lookup Service Helm Chart for Mojaloop
name: account-lookup-service
dependencies:
- name: account-lookup-service
  version: 9.3.0
  repository: "file://./chart-service"
  condition: account-lookup-service.enabled
- name: account-lookup-service-admin
  version: 9.3.0
  repository: "file://./chart-admin"
  condition: account-lookup-service-admin.enabled
- name: als-oracle-pathfinder
  version: 8.7.1
  repository: "file://../als-oracle-pathfinder"
  condition: als-oracle-pathfinder.enabled
# - name: percona-xtradb-cluster
#   version: 1.0.3
#   repository: https://kubernetes-charts.storage.googleapis.com
#   alias: mysql
#   condition: mysql.enabled
- name: percona-xtradb-cluster
  version: 1.0.4
  repository: "file://../percona-xtradb-cluster"
  alias: mysql
  condition: mysql.enabled
