# requirements.yaml
dependencies:
- name: centralledger
  version: 6.3.5
  repository: "file://../centralledger"
  condition: centralledger.enabled
## Deprecated - to be removed shortly
#- name: centraldirectory
#  version: 3.4.2
#  repository: "file://../centraldirectory"
#  condition: centraldirectory.enabled
- name: centralsettlement
  version: 6.3.0
  repository: "file://../centralsettlement"
  condition: centralsettlement.enabled
- name: centraleventprocessor
  version: 6.3.0
  repository: "file://../centraleventprocessor"
  condition: centraleventprocessor.enabled