# requirements.yaml
dependencies:
# - name: kafka
#   version: 0.7.2
#   repository: http://storage.googleapis.com/kubernetes-charts-incubator
#   alias: kafka
#   condition: kafka.enabled
- name: mongodb
  # 7.2.9 is the first version without the extensions/v1beta1 
  version: 7.2.9
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mongodb
  condition: mongodb.enabled
